name: modguard
channels:
  - defaults
dependencies:
  - ca-certificates=2025.2.25
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.16
  - pip=24.2
  - python=3.8.20
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - attrs==25.1.0
      - aws-cdk-asset-awscli-v1==2.2.226
      - aws-cdk-asset-node-proxy-agent-v6==2.1.0
      - aws-cdk-cloud-assembly-schema==40.7.0
      - aws-cdk-lib==2.182.0
      - cattrs==24.1.2
      - constructs==10.4.2
      - exceptiongroup==1.2.2
      - importlib-resources==6.4.5
      - jsii==1.108.0
      - publication==0.0.3
      - python-dateutil==2.9.0.post0
      - six==1.17.0
      - typeguard==2.13.3
      - typing-extensions==4.12.2
      - zipp==3.20.2
